targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/presentation/models/inputs/{{}}.dart': 'lib/presentation/models/inputs/generated/{{}}.g.dart'
            '^lib/presentation/models/outputs/{{}}.dart': 'lib/presentation/models/outputs/generated/{{}}.g.dart'