targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/presentation/models/requests/{{}}.dart': 'lib/presentation/models/requests/generated/{{}}.g.dart'
            '^lib/presentation/models/responses/{{}}.dart': 'lib/presentation/models/responses/generated/{{}}.g.dart'