targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/presentation/models/{{}}.dart': 'lib/presentation/models/generated/{{}}.g.dart'