# Use Dart official image
FROM dart:stable as build

# Set the working directory
WORKDIR /app

# Copy pubspec files - copy pubspec.yaml, pubspec.lock from current directory to directory in the container ./
COPY pubspec.* ./

# Resolve app dependencies
RUN dart pub get

# Copy source code to container
COPY . .
# Activate CLI for Dart Frog
RUN dart pub global activate dart_frog_cli
# Generating the production build
RUN dart pub global run dart_frog_cli:dart_frog build
# Resolve dependencies using already downloaded packages
RUN dart pub get --offline
# AOT-compile server to executable file
RUN dart compile exe build/bin/server.dart -o build/bin/server

# Use a minimal base image for production
FROM scratch

# Copy compiled executable from the build stage
COPY --from=build /runtime/ /
COPY --from=build /app/build/bin/server /app/bin/

# Expose the port used by Dart Frog
EXPOSE 8080

# Command to run the application
CMD ["/app/bin/server"]
