name: quecto_chat_backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  collection: ^1.19.0
  postgres: ^3.4.0
  dotenv: ^4.2.0

  # для работы с JWT-токенами
  dart_jsonwebtoken: ^2.14.1

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
